$(BUILD)/kernel-headers/Makefile:
	@echo "Unpacking kernel-headers for $(TARGET)"
	@mkdir -p $(BUILD)
	@cd $(BUILD); \
		rm -fr kernel-headers; \
		$(TAR) xf $(DEPS)/kernel-headers-3.12.6.tar.xz; \
		mv kernel-headers-3.12.6 kernel-headers

$(BUILD)/include/linux: $(BUILD)/kernel-headers/Makefile
	@echo "Building kernel-headers for $(TARGET)"
	@cd $(BUILD)/kernel-headers; \
		$(MAKE) ARCH=$(ARCH) prefix=/ DESTDIR=$(BUILD) $(LOGBUILD)

$(BUILD)/include/linux/in.h: $(BUILD)/include/linux
