$(BUILD)/kernel-headers/Makefile:
	@echo "Unpacking kernel-headers for $(TARGET)"
	@mkdir -p $(BUILD)
	@cd $(BUILD); \
		rm -fr kernel-headers; \
		$(TAR) xf $(TOOLCHAIN)/kernel-headers.xz; \

$(BUILD)/include/linux: $(BUILD)/kernel-headers/Makefile
	@echo "Building kernel-headers for $(TARGET)"
	@cd $(BUILD)/kernel-headers; \
		$(MAKE) ARCH=$(ARCH) prefix=/ DESTDIR=$(BUILD) install $(LOGBUILD)

kernel-headers: $(BUILD)/include/linux
