MBEDTLS_VERSION=2.2.1

$(BUILD)/lib/libmbedtls.a: build/tools
	@echo "Unpacking mbedtls for $(TARGET)"
	@mkdir -p $(BUILD)
	@cd $(BUILD); \
		rm -fr $(BUILD)/mbedtls; \
		$(TAR) zxf $(DEPS)/mbedtls-$(MBEDTLS_VERSION)-apache.tgz; \
		mv mbedtls-$(MBEDTLS_VERSION) mbedtls
	@echo "Building mbedtls for $(TARGET)"
	@cd $(BUILD)/mbedtls; \
		$(MAKE) $(LOGBUILD) ; \
		$(MAKE_INSTALL) DESTDIR=$(BUILD) $(LOGBUILD)

mbedtls: $(BUILD)/lib/libmbedtls.a
