#!/bin/sh

for i in arm-linux-musleabi \
	aarch64-linux-musl \
	arm-linux-musleabihf \
	i486-linux-musl \
	mipsel-linux-musl \
	mips-linux-musl \
	powerpc-linux-musl \
	x86_64-linux-musl; do
	echo Building target $i
	make TARGET=$i;
done

