#ifndef _EXTENSION_LUA_H
#define _EXTENSION_LUA_H

#define TLV_TYPE_EXTENSION_LUA 1

#define TLV_TYPE_LUA_CODE \
	MAKE_CUSTOM_TLV( \
		TLV_META_TYPE_STRING, \
		TLV_TYPE_EXTENSION_LUA, \
		TLV_EXTENSIONS + 1)

#endif
