#ifndef _EXTENSION_KEYLOGGER_H
#define _EXTENSION_KEYLOGGER_H

/*
 * TLV message types.
 */

#define TLV_TYPE_EXTENSION_KEYLOGGER 0

#define TLV_TYPE_KEYLOGGER_STATUS \
	MAKE_CUSTOM_TLV( \
		TLV_META_TYPE_BOOL, \
		TLV_TYPE_EXTENSION_KEYLOGGER, \
		TLV_EXTENSIONS + 1)

#define TLV_TYPE_KEYLOGGER_CAPTURE_RECORD \
	MAKE_CUSTOM_TLV( \
		TLV_META_TYPE_GROUP, \
		TLV_TYPE_EXTENSION_KEYLOGGER, \
		TLV_EXTENSIONS + 2)

#define TLV_TYPE_KEYLOGGER_CAPTURE_RECORD_NAME \
	MAKE_CUSTOM_TLV( \
		TLV_META_TYPE_STRING, \
		TLV_TYPE_EXTENSION_KEYLOGGER, \
		TLV_EXTENSIONS + 3)

#define TLV_TYPE_KEYLOGGER_CAPTURE_RECORD_DATA \
	MAKE_CUSTOM_TLV( \
		TLV_META_TYPE_RAW, \
		TLV_TYPE_EXTENSION_KEYLOGGER, \
		TLV_EXTENSIONS + 4)

#endif
